version: "3.8"
services:
    database:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - "33306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: grupotodo
        volumes:
            - mysql:/var/lib/mysql

    web:
        build: .
        ports:
            - "30080:80"
        volumes:
            - .:/var/www/html/
            - .composer:/.composer

        depends_on:
            - database

volumes:
    mysql:
